# SQL CARTO QUERY FUNCTION
# written for PUI2016_Python2

##### This notebook is set up to link as a default to the fb55 account.  To turn in the homework use the citibike dataset - check that you are able to read in about 40k rows

In [27]:
SQL_SOURCE = 'https://fb55.carto.com/api/v2/sql?q='

try:
    import urllib2 as ulib
except ImportError:
    import urllib3 as ulib

try:
    from StringIO import BytesIO as io
except ImportError:
    from io import BytesIO as io

try:
    from urllib import urlencode as urlencode
except ImportError:
    from urllib.parse import urlencode as urlencode
    
try:
    from urllib import urlopen as urlopen
except ImportError:
    from urllib.request import urlopen as urlopen
    
try:
    from urllib2 import HTTPError as HTTPError
except ImportError:
    from urllib.error import HTTPError as HTTPError

import ast
import pandas as pd

def queryCartoDB(query, formatting = 'CSV', source = SQL_SOURCE):
    '''queries carto datasets from a given carto account
    Arguments: 
    query - string: a valid sql query string
    format - outlut format  OPTIONAL (default CSV)
    source - a valid sql api endpoint OPTIONAL (default carto fb55 account)
    Returns:
    the return of the sql query AS A STRING
    NOTES:
    designed for the carto API, tested only with CSV return format'''
    
    
    data = urlencode({'format': formatting, 'q': query}).encode("utf-8")
    try:
        response = urlopen(source, data)
        return response.read()
    except HTTPError as e:
        raise (ValueError('\n'.join(ast.literal_eval(e.readline())['error'])))
        
def get_data(query):
    try:
        return pd.read_csv(io(queryCartoDB(query)), sep = ',')
    except ValueError as v:
        print (str(v))

In [37]:
test = '''
SELECT *
FROM citibike
'''

In [29]:
table = get_data(test)
table

,the_geom,start_station_name,the_geom_webmercator,field_1,start_station_longitude,tripduration,starttime,stoptime,start_station_id,cartodb_id,start_station_latitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,E 20 St & Park Ave,NaN,175,-73.987520,1090,2015-02-01 01:23:00+00,2015-02-01 01:42:00+00,503,107,40.738274,229,Great Jones St,40.727434,-73.993790,19718,Subscriber,1961.0,1
1,NaN,W 43 St & 10 Ave,NaN,1159,-73.994618,682,2015-02-01 10:55:00+00,2015-02-01 11:07:00+00,515,1088,40.760094,490,8 Ave & W 33 St,40.751551,-73.993934,21501,Subscriber,1981.0,1
2,NaN,E 6 St & Avenue B,NaN,2827,-73.981854,751,2015-02-01 13:59:00+00,2015-02-01 14:11:00+00,317,2759,40.724537,466,W 25 St & 6 Ave,40.743954,-73.991449,14788,Subscriber,1990.0,1
3,NaN,E 12 St & 3 Ave,NaN,4961,-73.988900,272,2015-02-01 17:28:00+00,2015-02-01 17:32:00+00,483,4893,40.732233,345,W 13 St & 6 Ave,40.736494,-73.997044,16219,Subscriber,1961.0,1
4,NaN,W 41 St & 8 Ave,NaN,6156,-73.990026,240,2015-02-01 21:36:00+00,2015-02-01 21:40:00+00,477,6090,40.756405,490,8 Ave & W 33 St,40.751551,-73.993934,18266,Customer,NaN,0
5,NaN,5 Ave & E 29 St,NaN,7433,-73.986831,376,2015-02-02 17:44:00+00,2015-02-02 17:50:00+00,474,7367,40.745168,537,Lexington Ave & E 24 St,40.740259,-73.984092,18048,Subscriber,1977.0,1
6,NaN,Allen St & Hester St,NaN,7779,-73.991908,1217,2015-02-02 20:12:00+00,2015-02-02 20:32:00+00,361,7712,40.716059,461,E 20 St & 2 Ave,40.735877,-73.982050,19732,Customer,NaN,0
7,NaN,E 39 St & 3 Ave,NaN,8327,-73.976049,441,2015-02-03 08:02:00+00,2015-02-03 08:10:00+00,167,8263,40.748901,526,E 33 St & 5 Ave,40.747659,-73.984907,21518,Subscriber,1975.0,1
8,NaN,10 Ave & W 28 St,NaN,9435,-74.001768,1475,2015-02-03 12:31:00+00,2015-02-03 12:56:00+00,489,9375,40.750664,455,1 Ave & E 44 St,40.750020,-73.969053,19863,Subscriber,1984.0,2
9,NaN,E 2 St & 2 Ave,NaN,10472,-73.990697,420,2015-02-03 16:45:00+00,2015-02-03 16:52:00+00,403,10411,40.725029,297,E 15 St & 3 Ave,40.734232,-73.986923,19257,Subscriber,1984.0,1
10,NaN,1 Ave & E 44 St,NaN,10931,-73.969053,876,2015-02-03 17:37:00+00,2015-02-03 17:52:00+00,455,10867,40.750020,477,W 41 St & 8 Ave,40.756405,-73.990026,17392,Subscriber,1977.0,1
11,NaN,W 45 St & 6 Ave,NaN,11361,-73.982912,640,2015-02-03 18:21:00+00,2015-02-03 18:32:00+00,493,11300,40.756800,440,E 45 St & 3 Ave,40.752554,-73.972826,21433,Subscriber,1981.0,1
12,NaN,W 18 St & 6 Ave,NaN,12173,-73.994564,571,2015-02-03 20:26:00+00,2015-02-03 20:35:00+00,168,12114,40.739713,494,W 26 St & 8 Ave,40.747348,-73.997236,19493,Subscriber,1964.0,1
13,NaN,E 58 St & 3 Ave,NaN,12211,-73.967245,821,2015-02-03 20:37:00+00,2015-02-03 20:50:00+00,305,12152,40.760958,515,W 43 St & 10 Ave,40.760094,-73.994618,16564,Subscriber,1983.0,1
14,NaN,E 33 St & 5 Ave,NaN,12560,-73.984907,376,2015-02-03 22:20:00+00,2015-02-03 22:26:00+00,526,12500,40.747659,507,E 25 St & 2 Ave,40.739126,-73.979738,19721,Subscriber,1991.0,1
15,NaN,W 31 St & 7 Ave,NaN,13239,-73.991600,770,2015-02-04 07:21:00+00,2015-02-04 07:34:00+00,379,13183,40.749156,461,E 20 St & 2 Ave,40.735877,-73.982050,15184,Subscriber,1987.0,2
16,NaN,5 Ave & E 29 St,NaN,13365,-73.986831,319,2015-02-04 07:35:00+00,2015-02-04 07:40:00+00,474,13312,40.745168,476,E 31 St & 3 Ave,40.743943,-73.979661,16067,Subscriber,1991.0,1
17,NaN,E 39 St & 2 Ave,NaN,13750,-73.973442,358,2015-02-04 08:11:00+00,2015-02-04 08:17:00+00,518,13702,40.747804,537,Lexington Ave & E 24 St,40.740259,-73.984092,19181,Subscriber,1991.0,1
18,NaN,10 Ave & W 28 St,NaN,14218,-74.001768,338,2015-02-04 08:45:00+00,2015-02-04 08:50:00+00,489,14172,40.750664,494,W 26 St & 8 Ave,40.747348,-73.997236,18840,Subscriber,1992.0,2
19,NaN,W 42 St & 8 Ave,NaN,14431,-73.990985,575,2015-02-04 08:59:00+00,2015-02-04 09:08:00+00,529,14384,40.757570,442,W 27 St & 7 Ave,40.746647,-73.993915,15151,Subscriber,1956.0,1
20,NaN,E 27 St & 1 Ave,NaN,15157,-73.976806,451,2015-02-04 10:10:00+00,2015-02-04 10:17:00+00,2012,15113,40.739445,518,E 39 St & 2 Ave,40.747804,-73.973442,20338,Subscriber,1990.0,2
21,NaN,Great Jones St,NaN,15669,-73.993790,548,2015-02-04 11:51:00+00,2015-02-04 12:00:00+00,229,15625,40.727434,284,Greenwich Ave & 8 Ave,40.739017,-74.002638,15482,Subscriber,1962.0,1
22,NaN,W 49 St & 8 Ave,NaN,16526,-73.987882,404,2015-02-04 14:08:00+00,2015-02-04 14:14:00+00,450,16481,40.762272,520,W 52 St & 5 Ave,40.759923,-73.976485,17488,Subscriber,1965.0,2
23,NaN,Broadway & W 24 St,NaN,16572,-73.989151,357,2015-02-04 14:15:00+00,2015-02-04 14:21:00+00,444,16527,40.742354,475,E 16 St & Irving Pl,40.735243,-73.987586,17453,Subscriber,1975.0,1
24,NaN,E 40 St & 5 Ave,NaN,18931,-73.981632,330,2015-02-04 18:02:00+00,2015-02-04 18:08:00+00,153,18880,40.752062,518,E 39 St & 2 Ave,40.747804,-73.973442,18973,Subscriber,1980.0,1
25,NaN,E 16 St & 5 Ave,NaN,19229,-73.992390,606,2015-02-04 18:19:00+00,2015-02-04 18:29:00+00,496,19177,40.737262,379,W 31 St & 7 Ave,40.749156,-73.991600,18362,Subscriber,1981.0,1
26,NaN,Broadway & W 36 St,NaN,20481,-73.987654,1001,2015-02-04 19:59:00+00,2015-02-04 20:15:00+00,267,20425,40.750977,504,1 Ave & E 15 St,40.732219,-73.981656,19935,Subscriber,1985.0,2
27,NaN,8 Ave & W 31 St,NaN,21285,-73.994811,1618,2015-02-04 21:58:00+00,2015-02-04 22:25:00+00,521,21228,40.750450,483,E 12 St & 3 Ave,40.732233,-73.988900,14660,Subscriber,1976.0,1
28,NaN,W 45 St & 6 Ave,NaN,23338,-73.982912,876,2015-02-05 08:29:00+00,2015-02-05 08:43:00+00,493,23298,40.756800,454,E 51 St & 1 Ave,40.754557,-73.965930,16891,Subscriber,1964.0,1
29,NaN,FDR Drive & E 35 St,NaN,23392,-73.971212,506,2015-02-05 08:32:00+00,2015-02-05 08:40:00+00,501,23353,40.744219,164,E 47 St & 2 Ave,40.753231,-73.970325,18208,Subscriber,1978.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46170,NaN,Washington Pl & Broadway,NaN,46170,-73.994046,812,2015-02-07 23:51:00+00,2015-02-08 00:05:00+00,335,46171,40.729039,435,W 21 St & 6 Ave,40.741740,-73.994156,15733,Subscriber,1988.0,1
46171,NaN,Allen St & Hester St,NaN,46171,-73.991908,647,2015-02-07 23:51:00+00,2015-02-08 00:02:00+00,361,46172,40.716059,504,1 Ave & E 15 St,40.732219,-73.981656,16931,Subscriber,1995.0,1
46172,NaN,Warren St & Church St,NaN,46172,-74.009106,563,2015-02-07 23:51:00+00,2015-02-08 00:00:00+00,152,46173,40.714740,401,Allen St & Rivington St,40.720196,-73.989978,17202,Subscriber,1987.0,1
46173,NaN,E 12 St & 3 Ave,NaN,46173,-73.988900,470,2015-02-07 23:51:00+00,2015-02-07 23:59:00+00,483,46174,40.732233,439,E 4 St & 2 Ave,40.726281,-73.989780,20314,Subscriber,1989.0,2
46174,NaN,Dean St & 4 Ave,NaN,46174,-73.978951,299,2015-02-07 23:51:00+00,2015-02-07 23:56:00+00,467,46175,40.683125,395,Bond St & Schermerhorn St,40.688070,-73.984106,21531,Subscriber,1989.0,1
46175,NaN,Allen St & Hester St,NaN,46175,-73.991908,629,2015-02-07 23:52:00+00,2015-02-08 00:02:00+00,361,46176,40.716059,504,1 Ave & E 15 St,40.732219,-73.981656,21491,Subscriber,1968.0,1
46176,NaN,Broadway & E 22 St,NaN,46176,-73.989551,499,2015-02-07 23:52:00+00,2015-02-08 00:00:00+00,402,46177,40.740343,380,W 4 St & 7 Ave S,40.734011,-74.002939,15367,Subscriber,1990.0,1
46177,NaN,Washington Pl & 6 Ave,NaN,46177,-74.000264,474,2015-02-07 23:52:00+00,2015-02-08 00:00:00+00,369,46178,40.732241,368,Carmine St & 6 Ave,40.730386,-74.002150,18978,Subscriber,1973.0,2
46178,NaN,E 31 St & 3 Ave,NaN,46178,-73.979661,345,2015-02-07 23:52:00+00,2015-02-07 23:58:00+00,476,46179,40.743943,504,1 Ave & E 15 St,40.732219,-73.981656,19507,Subscriber,1980.0,1
46179,NaN,Broadway & W 60 St,NaN,46179,-73.981918,829,2015-02-07 23:53:00+00,2015-02-08 00:07:00+00,499,46180,40.769155,160,E 37 St & Lexington Ave,40.748238,-73.978311,16936,Subscriber,1980.0,1
46180,NaN,Carmine St & 6 Ave,NaN,46180,-74.002150,776,2015-02-07 23:53:00+00,2015-02-08 00:05:00+00,368,46181,40.730386,531,Forsyth St & Broome St,40.718939,-73.992663,18689,Subscriber,1982.0,1
46181,NaN,W 52 St & 5 Ave,NaN,46181,-73.976485,697,2015-02-07 23:53:00+00,2015-02-08 00:05:00+00,520,46182,40.759923,478,11 Ave & W 41 St,40.760301,-73.998842,15781,Subscriber,1972.0,1
46182,NaN,Dean St & 4 Ave,NaN,46182,-73.978951,1703,2015-02-07 23:54:00+00,2015-02-08 00:23:00+00,467,46183,40.683125,471,Grand St & Havemeyer St,40.712868,-73.956981,15081,Subscriber,1988.0,1
46183,NaN,9 Ave & W 45 St,NaN,46183,-73.991255,922,2015-02-07 23:54:00+00,2015-02-08 00:10:00+00,479,46184,40.760193,247,Perry St & Bleecker St,40.735354,-74.004831,21672,Subscriber,1983.0,1
46184,NaN,Broadway & W 58 St,NaN,46184,-73.981693,849,2015-02-07 23:54:00+00,2015-02-08 00:08:00+00,457,46185,40.766953,488,W 39 St & 9 Ave,40.756458,-73.993722,16336,Subscriber,1970.0,1
46185,NaN,Broadway & W 58 St,NaN,46185,-73.981693,826,2015-02-07 23:54:00+00,2015-02-08 00:08:00+00,457,46186,40.766953,488,W 39 St & 9 Ave,40.756458,-73.993722,21609,Subscriber,1973.0,1
46186,NaN,Watts St & Greenwich St,NaN,46186,-74.009660,473,2015-02-07 23:54:00+00,2015-02-08 00:02:00+00,328,46187,40.724055,3002,South End Ave & Liberty St,40.711512,-74.015756,19470,Subscriber,1964.0,1
46187,NaN,W 51 St & 6 Ave,NaN,46187,-73.980420,332,2015-02-07 23:54:00+00,2015-02-07 23:59:00+00,510,46188,40.760660,450,W 49 St & 8 Ave,40.762272,-73.987882,18167,Subscriber,1960.0,1
46188,NaN,University Pl & E 14 St,NaN,46188,-73.992005,456,2015-02-07 23:55:00+00,2015-02-08 00:03:00+00,382,46189,40.734927,404,9 Ave & W 14 St,40.740583,-74.005509,15929,Subscriber,1987.0,1
46189,NaN,W 11 St & 6 Ave,NaN,46189,-73.998004,327,2015-02-07 23:55:00+00,2015-02-08 00:01:00+00,254,46190,40.735324,466,W 25 St & 6 Ave,40.743954,-73.991449,17541,Subscriber,1983.0,1
46190,NaN,W 17 St & 8 Ave,NaN,46190,-74.001497,306,2015-02-07 23:55:00+00,2015-02-08 00:01:00+00,116,46191,40.741776,494,W 26 St & 8 Ave,40.747348,-73.997236,14736,Subscriber,1983.0,2
46191,NaN,W 47 St & 10 Ave,NaN,46191,-73.993012,1248,2015-02-07 23:56:00+00,2015-02-08 00:17:00+00,495,46192,40.762699,432,E 7 St & Avenue A,40.726218,-73.983799,16300,Subscriber,1984.0,1
46192,NaN,Warren St & Church St,NaN,46192,-74.009106,1165,2015-02-07 23:56:00+00,2015-02-08 00:15:00+00,152,46193,40.714740,325,E 19 St & 3 Ave,40.736245,-73.984738,16978,Subscriber,1959.0,1
46193,NaN,E 20 St & 2 Ave,NaN,46193,-73.982050,993,2015-02-07 23:56:00+00,2015-02-08 00:13:00+00,461,46194,40.735877,295,Pike St & E Broadway,40.714067,-73.992939,16722,Subscriber,1974.0,1
46194,NaN,1 Ave & E 44 St,NaN,46194,-73.969053,1422,2015-02-07 23:57:00+00,2015-02-08 00:20:00+00,455,46195,40.750020,265,Stanton St & Chrystie St,40.722293,-73.991475,20184,Subscriber,1960.0,2
46195,NaN,W 20 St & 8 Ave,NaN,46195,-74.000040,689,2015-02-07 23:57:00+00,2015-02-08 00:08:00+00,470,46196,40.743453,325,E 19 St & 3 Ave,40.736245,-73.984738,15585,Subscriber,1953.0,1
46196,NaN,5 Ave & E 29 St,NaN,46196,-73.986831,428,2015-02-07 23:57:00+00,2015-02-08 00:04:00+00,474,46197,40.745168,325,E 19 St & 3 Ave,40.736245,-73.984738,16395,Subscriber,1986.0,2
46197,NaN,5 Ave & E 29 St,NaN,46197,-73.986831,392,2015-02-07 23:57:00+00,2015-02-08 00:03:00+00,474,46198,40.745168,325,E 19 St & 3 Ave,40.736245,-73.984738,15545,Subscriber,1986.0,1
46198,NaN,Carmine St & 6 Ave,NaN,46198,-74.002150,548,2015-02-07 23:58:00+00,2015-02-08 00:08:00+00,368,46199,40.730386,334,W 20 St & 7 Ave,40.742388,-73.997262,19540,Subscriber,1983.0,2
46199,NaN,E 4 St & 2 Ave,NaN,46199,-73.989780,917,2015-02-07 23:59:00+00,2015-02-08 00:15:00+00,439,46200,40.726281,417,Barclay St & Church St,40.712912,-74.010202,20998,Subscriber,1965.0,2

# TASK 1 ------ Familiarize with SQL Clauses

## Sort data by start_station_id, tripduration 
### (Only checking trips with duration <= 3 hours)

In [118]:
test = '''
SELECT start_station_id, tripduration FROM citibike
WHERE tripduration <= 10800
ORDER BY start_station_id ASC;
'''

In [119]:

table = get_data(test)
table.head()

   start_station_id  tripduration
0                72           747
1                72           388
2                72          1127
3                72          1535
4                72           586

## Only show the top/last 10 records

In [122]:
test = '''
SELECT *
FROM citibike
LIMIT 10;
'''
table = get_data(test)
table

,the_geom,start_station_name,the_geom_webmercator,field_1,start_station_longitude,tripduration,starttime,stoptime,start_station_id,cartodb_id,start_station_latitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,E 20 St & Park Ave,NaN,175,-73.987520,1090,2015-02-01 01:23:00+00,2015-02-01 01:42:00+00,503,107,40.738274,229,Great Jones St,40.727434,-73.993790,19718,Subscriber,1961.0,1
1,NaN,W 43 St & 10 Ave,NaN,1159,-73.994618,682,2015-02-01 10:55:00+00,2015-02-01 11:07:00+00,515,1088,40.760094,490,8 Ave & W 33 St,40.751551,-73.993934,21501,Subscriber,1981.0,1
2,NaN,E 6 St & Avenue B,NaN,2827,-73.981854,751,2015-02-01 13:59:00+00,2015-02-01 14:11:00+00,317,2759,40.724537,466,W 25 St & 6 Ave,40.743954,-73.991449,14788,Subscriber,1990.0,1
3,NaN,E 12 St & 3 Ave,NaN,4961,-73.988900,272,2015-02-01 17:28:00+00,2015-02-01 17:32:00+00,483,4893,40.732233,345,W 13 St & 6 Ave,40.736494,-73.997044,16219,Subscriber,1961.0,1
4,NaN,W 41 St & 8 Ave,NaN,6156,-73.990026,240,2015-02-01 21:36:00+00,2015-02-01 21:40:00+00,477,6090,40.756405,490,8 Ave & W 33 St,40.751551,-73.993934,18266,Customer,NaN,0
5,NaN,5 Ave & E 29 St,NaN,7433,-73.986831,376,2015-02-02 17:44:00+00,2015-02-02 17:50:00+00,474,7367,40.745168,537,Lexington Ave & E 24 St,40.740259,-73.984092,18048,Subscriber,1977.0,1
6,NaN,Allen St & Hester St,NaN,7779,-73.991908,1217,2015-02-02 20:12:00+00,2015-02-02 20:32:00+00,361,7712,40.716059,461,E 20 St & 2 Ave,40.735877,-73.982050,19732,Customer,NaN,0
7,NaN,E 39 St & 3 Ave,NaN,8327,-73.976049,441,2015-02-03 08:02:00+00,2015-02-03 08:10:00+00,167,8263,40.748901,526,E 33 St & 5 Ave,40.747659,-73.984907,21518,Subscriber,1975.0,1
8,NaN,10 Ave & W 28 St,NaN,9435,-74.001768,1475,2015-02-03 12:31:00+00,2015-02-03 12:56:00+00,489,9375,40.750664,455,1 Ave & E 44 St,40.750020,-73.969053,19863,Subscriber,1984.0,2
9,NaN,E 2 St & 2 Ave,NaN,10472,-73.990697,420,2015-02-03 16:45:00+00,2015-02-03 16:52:00+00,403,10411,40.725029,297,E 15 St & 3 Ave,40.734232,-73.986923,19257,Subscriber,1984.0,1

In [123]:
test = '''
SELECT *
FROM citibike
LIMIT 10 OFFSET 46200 - 10;
'''
table = get_data(test)
table

,the_geom,start_station_name,the_geom_webmercator,field_1,start_station_longitude,tripduration,starttime,stoptime,start_station_id,cartodb_id,start_station_latitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,W 17 St & 8 Ave,NaN,46190,-74.001497,306,2015-02-07 23:55:00+00,2015-02-08 00:01:00+00,116,46191,40.741776,494,W 26 St & 8 Ave,40.747348,-73.997236,14736,Subscriber,1983,2
1,NaN,W 47 St & 10 Ave,NaN,46191,-73.993012,1248,2015-02-07 23:56:00+00,2015-02-08 00:17:00+00,495,46192,40.762699,432,E 7 St & Avenue A,40.726218,-73.983799,16300,Subscriber,1984,1
2,NaN,Warren St & Church St,NaN,46192,-74.009106,1165,2015-02-07 23:56:00+00,2015-02-08 00:15:00+00,152,46193,40.714740,325,E 19 St & 3 Ave,40.736245,-73.984738,16978,Subscriber,1959,1
3,NaN,E 20 St & 2 Ave,NaN,46193,-73.982050,993,2015-02-07 23:56:00+00,2015-02-08 00:13:00+00,461,46194,40.735877,295,Pike St & E Broadway,40.714067,-73.992939,16722,Subscriber,1974,1
4,NaN,1 Ave & E 44 St,NaN,46194,-73.969053,1422,2015-02-07 23:57:00+00,2015-02-08 00:20:00+00,455,46195,40.750020,265,Stanton St & Chrystie St,40.722293,-73.991475,20184,Subscriber,1960,2
5,NaN,W 20 St & 8 Ave,NaN,46195,-74.000040,689,2015-02-07 23:57:00+00,2015-02-08 00:08:00+00,470,46196,40.743453,325,E 19 St & 3 Ave,40.736245,-73.984738,15585,Subscriber,1953,1
6,NaN,5 Ave & E 29 St,NaN,46196,-73.986831,428,2015-02-07 23:57:00+00,2015-02-08 00:04:00+00,474,46197,40.745168,325,E 19 St & 3 Ave,40.736245,-73.984738,16395,Subscriber,1986,2
7,NaN,5 Ave & E 29 St,NaN,46197,-73.986831,392,2015-02-07 23:57:00+00,2015-02-08 00:03:00+00,474,46198,40.745168,325,E 19 St & 3 Ave,40.736245,-73.984738,15545,Subscriber,1986,1
8,NaN,Carmine St & 6 Ave,NaN,46198,-74.002150,548,2015-02-07 23:58:00+00,2015-02-08 00:08:00+00,368,46199,40.730386,334,W 20 St & 7 Ave,40.742388,-73.997262,19540,Subscriber,1983,2
9,NaN,E 4 St & 2 Ave,NaN,46199,-73.989780,917,2015-02-07 23:59:00+00,2015-02-08 00:15:00+00,439,46200,40.726281,417,Barclay St & Church St,40.712912,-74.010202,20998,Subscriber,1965,2

## List all unique start_station_id values

In [124]:
test = '''
SELECT DISTINCT start_station_id FROM citibike
WHERE start_station_id IS NOT NULL;
'''

table = get_data(test)
table.head(5)

   start_station_id  Unnamed: 1
0               120         NaN
1               285         NaN
2               251         NaN
3               195         NaN
4               453         NaN

## Aggregation functions
### Count the number of trips

In [125]:
test = '''
SELECT count(*)
FROM citibike;
'''
table = get_data(test)
table

   count  Unnamed: 1
0  46200         NaN

### Find the average/min/max trip duration

In [126]:
test = '''
SELECT MIN(tripduration) as Min_Tripduration FROM citibike;
'''

table = get_data(test)
print(table)

test = '''
SELECT MAX(tripduration) FROM citibike;
'''

table = get_data(test)
print(table)

test = '''
SELECT AVG(tripduration) FROM citibike;
'''

table = get_data(test)
print(table)

   min_tripduration  Unnamed: 1
0                60         NaN
     max  Unnamed: 1
0  43016         NaN
          avg  Unnamed: 1
0  675.865823         NaN

# TASK 2 ------ Working with date/time

## Selecting trips started on Feb-02-2015 only

In [127]:
test = '''SELECT * FROM citibike
WHERE starttime >= '2/2/2015 0:00'
and starttime <= '2/2/2015 23:59'
'''
table = get_data(test)
table

,the_geom,start_station_name,the_geom_webmercator,field_1,start_station_longitude,tripduration,starttime,stoptime,start_station_id,cartodb_id,start_station_latitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,5 Ave & E 29 St,NaN,7433,-73.986831,376,2015-02-02 17:44:00+00,2015-02-02 17:50:00+00,474,7367,40.745168,537,Lexington Ave & E 24 St,40.740259,-73.984092,18048,Subscriber,1977.0,1
1,NaN,Allen St & Hester St,NaN,7779,-73.991908,1217,2015-02-02 20:12:00+00,2015-02-02 20:32:00+00,361,7712,40.716059,461,E 20 St & 2 Ave,40.735877,-73.982050,19732,Customer,NaN,0
2,NaN,E 5 St & Avenue C,NaN,11,-73.979955,1312,2015-02-02 11:07:00+00,2015-02-02 11:29:00+00,393,6920,40.722992,476,E 31 St & 3 Ave,40.743943,-73.979661,17720,Subscriber,1955.0,1
3,NaN,9 Ave & W 16 St,NaN,627,-74.004432,444,2015-02-02 00:40:00+00,2015-02-02 00:48:00+00,463,6477,40.742065,489,10 Ave & W 28 St,40.750664,-74.001768,20233,Subscriber,1971.0,1
4,NaN,9 Ave & W 16 St,NaN,991,-74.004432,438,2015-02-02 00:40:00+00,2015-02-02 00:47:00+00,463,6478,40.742065,489,10 Ave & W 28 St,40.750664,-74.001768,20264,Subscriber,1981.0,2
5,NaN,W 33 St & 7 Ave,NaN,1037,-73.990931,498,2015-02-02 06:20:00+00,2015-02-02 06:28:00+00,492,6526,40.750200,493,W 45 St & 6 Ave,40.756800,-73.982912,16013,Subscriber,1962.0,2
6,NaN,W 27 St & 7 Ave,NaN,6510,-73.993915,199,2015-02-02 00:02:00+00,2015-02-02 00:05:00+00,442,6442,40.746647,489,10 Ave & W 28 St,40.750664,-74.001768,20684,Subscriber,1992.0,1
7,NaN,E 11 St & 1 Ave,NaN,6511,-73.984267,418,2015-02-02 00:03:00+00,2015-02-02 00:10:00+00,326,6443,40.729538,349,Rivington St & Ridge St,40.718502,-73.983299,16094,Subscriber,1964.0,2
8,NaN,Peck Slip & Front St,NaN,6512,-74.001670,276,2015-02-02 00:04:00+00,2015-02-02 00:09:00+00,279,6444,40.707873,415,Pearl St & Hanover Square,40.704718,-74.009260,17362,Subscriber,1974.0,1
9,NaN,E 16 St & 5 Ave,NaN,6513,-73.992390,420,2015-02-02 00:06:00+00,2015-02-02 00:13:00+00,496,6445,40.737262,237,E 11 St & 2 Ave,40.730473,-73.986724,15475,Subscriber,1992.0,2
10,NaN,W 41 St & 8 Ave,NaN,6514,-73.990026,304,2015-02-02 00:07:00+00,2015-02-02 00:12:00+00,477,6446,40.756405,450,W 49 St & 8 Ave,40.762272,-73.987882,16272,Subscriber,1968.0,1
11,NaN,Dean St & 4 Ave,NaN,6515,-73.978951,622,2015-02-02 00:08:00+00,2015-02-02 00:18:00+00,467,6447,40.683125,391,Clark St & Henry St,40.697601,-73.993446,16370,Subscriber,1979.0,1
12,NaN,9 Ave & W 18 St,NaN,6516,-74.003664,371,2015-02-02 00:09:00+00,2015-02-02 00:15:00+00,434,6448,40.743174,482,W 15 St & 7 Ave,40.739355,-73.999318,19437,Subscriber,1963.0,1
13,NaN,Reade St & Broadway,NaN,6517,-74.005628,477,2015-02-02 00:11:00+00,2015-02-02 00:19:00+00,330,6449,40.714505,2008,Little West St & 1 Pl,40.705693,-74.016777,21211,Subscriber,1982.0,1
14,NaN,8 Ave & W 31 St,NaN,6518,-73.994811,743,2015-02-02 00:12:00+00,2015-02-02 00:25:00+00,521,6450,40.750450,423,W 54 St & 9 Ave,40.765849,-73.986905,21417,Subscriber,1978.0,2
15,NaN,1 Ave & E 15 St,NaN,6519,-73.981656,599,2015-02-02 00:12:00+00,2015-02-02 00:22:00+00,504,6451,40.732219,453,W 22 St & 8 Ave,40.744751,-73.999154,15722,Subscriber,1956.0,1
16,NaN,Broadway & E 14 St,NaN,6520,-73.990741,345,2015-02-02 00:12:00+00,2015-02-02 00:18:00+00,285,6452,40.734546,236,St Marks Pl & 2 Ave,40.728419,-73.987140,18972,Subscriber,1962.0,1
17,NaN,E 2 St & Avenue B,NaN,6521,-73.983688,721,2015-02-02 00:13:00+00,2015-02-02 00:25:00+00,301,6453,40.722174,476,E 31 St & 3 Ave,40.743943,-73.979661,19628,Subscriber,1980.0,1
18,NaN,Peck Slip & Front St,NaN,6522,-74.001670,182,2015-02-02 00:13:00+00,2015-02-02 00:16:00+00,279,6454,40.707873,376,John St & William St,40.708621,-74.007222,15169,Subscriber,1978.0,1
19,NaN,Columbia St & Rivington St,NaN,6523,-73.980166,154,2015-02-02 00:13:00+00,2015-02-02 00:16:00+00,342,6455,40.717400,411,E 6 St & Avenue D,40.722281,-73.976687,17533,Subscriber,1997.0,1
20,NaN,W 20 St & 8 Ave,NaN,6524,-74.000040,435,2015-02-02 00:14:00+00,2015-02-02 00:21:00+00,470,6456,40.743453,491,E 24 St & Park Ave S,40.740964,-73.986022,19761,Subscriber,1983.0,1
21,NaN,St Marks Pl & 2 Ave,NaN,6525,-73.987140,310,2015-02-02 00:15:00+00,2015-02-02 00:20:00+00,236,6457,40.728419,393,E 5 St & Avenue C,40.722992,-73.979955,17267,Subscriber,1993.0,1
22,NaN,W 20 St & 8 Ave,NaN,6526,-74.000040,1274,2015-02-02 00:16:00+00,2015-02-02 00:37:00+00,470,6458,40.743453,470,W 20 St & 8 Ave,40.743453,-74.000040,18691,Subscriber,1964.0,1
23,NaN,W 37 St & 5 Ave,NaN,6527,-73.983390,642,2015-02-02 00:18:00+00,2015-02-02 00:29:00+00,485,6459,40.750380,174,E 25 St & 1 Ave,40.738177,-73.977387,17106,Subscriber,1977.0,1
24,NaN,W 13 St & 6 Ave,NaN,6528,-73.997044,256,2015-02-02 00:18:00+00,2015-02-02 00:22:00+00,345,6460,40.736494,483,E 12 St & 3 Ave,40.732233,-73.988900,20009,Subscriber,1973.0,1
25,NaN,10 Ave & W 28 St,NaN,6529,-74.001768,334,2015-02-02 00:19:00+00,2015-02-02 00:25:00+00,489,6461,40.750664,442,W 27 St & 7 Ave,40.746647,-73.993915,18777,Subscriber,1979.0,1
26,NaN,E 25 St & 2 Ave,NaN,6530,-73.979738,90,2015-02-02 00:19:00+00,2015-02-02 00:20:00+00,507,6462,40.739126,174,E 25 St & 1 Ave,40.738177,-73.977387,15357,Subscriber,1989.0,1
27,NaN,W 4 St & 7 Ave S,NaN,6531,-74.002939,203,2015-02-02 00:20:00+00,2015-02-02 00:23:00+00,380,6463,40.734011,405,Washington St & Gansevoort St,40.739323,-74.008119,18487,Subscriber,1983.0,1
28,NaN,W 20 St & 7 Ave,NaN,6532,-73.997262,649,2015-02-02 00:22:00+00,2015-02-02 00:32:00+00,334,6464,40.742388,439,E 4 St & 2 Ave,40.726281,-73.989780,20863,Subscriber,1981.0,1
29,NaN,W 46 St & 11 Ave,NaN,6533,-73.996674,319,2015-02-02 00:23:00+00,2015-02-02 00:29:00+00,508,6465,40.763414,448,W 37 St & 10 Ave,40.756604,-73.997901,16539,Subscriber,1970.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,NaN,Allen St & E Houston St,NaN,7938,-73.989111,722,2015-02-02 23:08:00+00,2015-02-02 23:20:00+00,312,7871,40.722055,380,W 4 St & 7 Ave S,40.734011,-74.002939,20572,Subscriber,1985.0,1
1430,NaN,Broadway & W 29 St,NaN,7939,-73.988557,274,2015-02-02 23:08:00+00,2015-02-02 23:12:00+00,486,7872,40.746201,491,E 24 St & Park Ave S,40.740964,-73.986022,20338,Subscriber,1981.0,1
1431,NaN,W 56 St & 6 Ave,NaN,7940,-73.977225,951,2015-02-02 23:11:00+00,2015-02-02 23:27:00+00,352,7873,40.763406,515,W 43 St & 10 Ave,40.760094,-73.994618,15826,Subscriber,1978.0,1
1432,NaN,10 Ave & W 28 St,NaN,7941,-74.001768,276,2015-02-02 23:16:00+00,2015-02-02 23:20:00+00,489,7874,40.750664,521,8 Ave & W 31 St,40.750450,-73.994811,18325,Subscriber,1990.0,1
1433,NaN,W 26 St & 8 Ave,NaN,7942,-73.997236,426,2015-02-02 23:17:00+00,2015-02-02 23:24:00+00,494,7875,40.747348,434,9 Ave & W 18 St,40.743174,-74.003664,16654,Subscriber,1977.0,1
1434,NaN,Broadway & E 22 St,NaN,7943,-73.989551,578,2015-02-02 23:19:00+00,2015-02-02 23:28:00+00,402,7876,40.740343,229,Great Jones St,40.727434,-73.993790,20902,Subscriber,1966.0,1
1435,NaN,E 47 St & 2 Ave,NaN,7944,-73.970325,2621,2015-02-02 23:22:00+00,2015-02-03 00:06:00+00,164,7877,40.753231,2017,E 43 St & 2 Ave,40.750224,-73.971214,20796,Subscriber,1954.0,1
1436,NaN,Broadway & W 32 St,NaN,7945,-73.988084,621,2015-02-02 23:22:00+00,2015-02-02 23:32:00+00,498,7878,40.748549,449,W 52 St & 9 Ave,40.764618,-73.987895,20160,Subscriber,1989.0,1
1437,NaN,8 Ave & W 31 St,NaN,7946,-73.994811,323,2015-02-02 23:23:00+00,2015-02-02 23:29:00+00,521,7879,40.750450,477,W 41 St & 8 Ave,40.756405,-73.990026,17392,Subscriber,1974.0,1
1438,NaN,9 Ave & W 18 St,NaN,7947,-74.003664,393,2015-02-02 23:24:00+00,2015-02-02 23:31:00+00,434,7880,40.743174,482,W 15 St & 7 Ave,40.739355,-73.999318,17263,Subscriber,1963.0,1
1439,NaN,LaGuardia Pl & W 3 St,NaN,7948,-73.998102,597,2015-02-02 23:25:00+00,2015-02-02 23:35:00+00,161,7881,40.729170,497,E 17 St & Broadway,40.737050,-73.990093,19858,Subscriber,1955.0,1
1440,NaN,W 26 St & 8 Ave,NaN,7949,-73.997236,244,2015-02-02 23:25:00+00,2015-02-02 23:30:00+00,494,7882,40.747348,462,W 22 St & 10 Ave,40.746920,-74.004519,20319,Subscriber,1979.0,1
1441,NaN,Cliff St & Fulton St,NaN,7950,-74.005301,1023,2015-02-02 23:26:00+00,2015-02-02 23:43:00+00,306,7883,40.708235,127,Barrow St & Hudson St,40.731724,-74.006744,21600,Subscriber,1977.0,1
1442,NaN,Rivington St & Ridge St,NaN,7951,-73.983299,419,2015-02-02 23:31:00+00,2015-02-02 23:38:00+00,349,7884,40.718502,473,Rivington St & Chrystie St,40.721101,-73.991925,18791,Subscriber,1986.0,1
1443,NaN,W 49 St & 8 Ave,NaN,7952,-73.987882,1429,2015-02-02 23:32:00+00,2015-02-02 23:55:00+00,450,7885,40.762272,358,Christopher St & Greenwich St,40.732916,-74.007114,17730,Subscriber,1966.0,1
1444,NaN,Pershing Square North,NaN,7953,-73.977706,676,2015-02-02 23:32:00+00,2015-02-02 23:44:00+00,519,7886,40.751873,477,W 41 St & 8 Ave,40.756405,-73.990026,18147,Subscriber,1980.0,1
1445,NaN,E 30 St & Park Ave S,NaN,7954,-73.983035,879,2015-02-02 23:33:00+00,2015-02-02 23:48:00+00,546,7887,40.744449,489,10 Ave & W 28 St,40.750664,-74.001768,20249,Subscriber,1959.0,1
1446,NaN,Sullivan St & Washington Sq,NaN,7955,-73.999061,593,2015-02-02 23:35:00+00,2015-02-02 23:45:00+00,336,7888,40.730477,432,E 7 St & Avenue A,40.726218,-73.983799,18078,Subscriber,1988.0,1
1447,NaN,W 42 St & 8 Ave,NaN,7956,-73.990985,839,2015-02-02 23:36:00+00,2015-02-02 23:50:00+00,529,7889,40.757570,164,E 47 St & 2 Ave,40.753231,-73.970325,16808,Subscriber,1983.0,1
1448,NaN,Broadway & E 22 St,NaN,7957,-73.989551,560,2015-02-02 23:37:00+00,2015-02-02 23:46:00+00,402,7890,40.740343,368,Carmine St & 6 Ave,40.730386,-74.002150,21355,Subscriber,1986.0,1
1449,NaN,1 Ave & E 15 St,NaN,7958,-73.981656,165,2015-02-02 23:37:00+00,2015-02-02 23:40:00+00,504,7891,40.732219,511,E 14 St & Avenue B,40.729387,-73.977724,15359,Subscriber,1994.0,1
1450,NaN,6 Ave & W 33 St,NaN,7959,-73.988484,813,2015-02-02 23:42:00+00,2015-02-02 23:56:00+00,505,7892,40.749013,489,10 Ave & W 28 St,40.750664,-74.001768,18250,Subscriber,1982.0,2
1451,NaN,9 Ave & W 22 St,NaN,7960,-74.001971,764,2015-02-02 23:42:00+00,2015-02-02 23:55:00+00,509,7893,40.745497,507,E 25 St & 2 Ave,40.739126,-73.979738,16969,Subscriber,1987.0,1
1452,NaN,E 16 St & 5 Ave,NaN,7961,-73.992390,2111,2015-02-02 23:43:00+00,2015-02-03 00:18:00+00,496,7894,40.737262,397,Fulton St & Clermont Ave,40.684157,-73.969223,18825,Subscriber,1979.0,1
1453,NaN,E 10 St & 5 Ave,NaN,7962,-73.995101,518,2015-02-02 23:43:00+00,2015-02-02 23:52:00+00,280,7895,40.733320,439,E 4 St & 2 Ave,40.726281,-73.989780,19000,Subscriber,1983.0,1
1454,NaN,W 44 St & 5 Ave,NaN,7963,-73.980144,371,2015-02-02 23:45:00+00,2015-02-02 23:52:00+00,484,7896,40.755003,440,E 45 St & 3 Ave,40.752554,-73.972826,20723,Subscriber,1977.0,1
1455,NaN,Spruce St & Nassau St,NaN,7964,-74.005524,188,2015-02-02 23:47:00+00,2015-02-02 23:50:00+00,224,7897,40.711464,417,Barclay St & Church St,40.712912,-74.010202,16528,Subscriber,1988.0,1
1456,NaN,W 13 St & 6 Ave,NaN,7965,-73.997044,689,2015-02-02 23:50:00+00,2015-02-03 00:02:00+00,345,7898,40.736494,394,E 9 St & Avenue C,40.725213,-73.977688,16541,Subscriber,1988.0,1
1457,NaN,W 22 St & 8 Ave,NaN,7966,-73.999154,634,2015-02-02 23:55:00+00,2015-02-03 00:05:00+00,453,7899,40.744751,537,Lexington Ave & E 24 St,40.740259,-73.984092,14878,Subscriber,1961.0,1
1458,NaN,Broadway & E 14 St,NaN,7967,-73.990741,733,2015-02-02 23:58:00+00,2015-02-03 00:10:00+00,285,7900,40.734546,302,Avenue D & E 3 St,40.720828,-73.977932,16326,Subscriber,1976.0,2

## Selecting trips started on the weekends

In [128]:
test = '''SELECT * FROM citibike
WHERE starttime >= '2/1/2015 0:00'
and starttime <= '2/1/2015 23:59'
'''
table = get_data(test)
table

,the_geom,start_station_name,the_geom_webmercator,field_1,start_station_longitude,tripduration,starttime,stoptime,start_station_id,cartodb_id,start_station_latitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,E 20 St & Park Ave,NaN,175,-73.987520,1090,2015-02-01 01:23:00+00,2015-02-01 01:42:00+00,503,107,40.738274,229,Great Jones St,40.727434,-73.993790,19718,Subscriber,1961.0,1
1,NaN,W 43 St & 10 Ave,NaN,1159,-73.994618,682,2015-02-01 10:55:00+00,2015-02-01 11:07:00+00,515,1088,40.760094,490,8 Ave & W 33 St,40.751551,-73.993934,21501,Subscriber,1981.0,1
2,NaN,E 6 St & Avenue B,NaN,2827,-73.981854,751,2015-02-01 13:59:00+00,2015-02-01 14:11:00+00,317,2759,40.724537,466,W 25 St & 6 Ave,40.743954,-73.991449,14788,Subscriber,1990.0,1
3,NaN,E 12 St & 3 Ave,NaN,4961,-73.988900,272,2015-02-01 17:28:00+00,2015-02-01 17:32:00+00,483,4893,40.732233,345,W 13 St & 6 Ave,40.736494,-73.997044,16219,Subscriber,1961.0,1
4,NaN,W 41 St & 8 Ave,NaN,6156,-73.990026,240,2015-02-01 21:36:00+00,2015-02-01 21:40:00+00,477,6090,40.756405,490,8 Ave & W 33 St,40.751551,-73.993934,18266,Customer,NaN,0
5,NaN,8 Ave & W 33 St,NaN,0,-73.993934,447,2015-02-01 01:11:00+00,2015-02-01 01:19:00+00,490,93,40.751551,479,9 Ave & W 45 St,40.760193,-73.991255,15185,Subscriber,1983.0,2
6,NaN,Broadway & W 39 St,NaN,1,-73.987216,277,2015-02-01 10:26:00+00,2015-02-01 10:30:00+00,533,847,40.752996,515,W 43 St & 10 Ave,40.760094,-73.994618,16452,Subscriber,1978.0,1
7,NaN,W 18 St & 6 Ave,NaN,2,-73.994564,526,2015-02-01 11:07:00+00,2015-02-01 11:16:00+00,168,1180,40.739713,521,8 Ave & W 31 St,40.750450,-73.994811,16741,Subscriber,1984.0,1
8,NaN,Broadway & E 22 St,NaN,3,-73.989551,502,2015-02-01 12:37:00+00,2015-02-01 12:46:00+00,402,1971,40.740343,459,W 20 St & 11 Ave,40.746745,-74.007756,16951,Subscriber,1983.0,1
9,NaN,W 46 St & 11 Ave,NaN,4,-73.996674,943,2015-02-01 12:46:00+00,2015-02-01 13:02:00+00,508,2053,40.763414,521,8 Ave & W 31 St,40.750450,-73.994811,16897,Subscriber,1966.0,2
10,NaN,Great Jones St,NaN,5,-73.993790,563,2015-02-01 12:54:00+00,2015-02-01 13:03:00+00,229,2138,40.727434,346,Bank St & Hudson St,40.736529,-74.006180,16722,Subscriber,1984.0,1
11,NaN,Carmine St & 6 Ave,NaN,6,-74.002150,519,2015-02-01 15:21:00+00,2015-02-01 15:29:00+00,368,3591,40.730386,503,E 20 St & Park Ave,40.738274,-73.987520,15196,Subscriber,1968.0,1
12,NaN,E 12 St & 3 Ave,NaN,7,-73.988900,500,2015-02-01 17:38:00+00,2015-02-01 17:47:00+00,483,4983,40.732233,435,W 21 St & 6 Ave,40.741740,-73.994156,19409,Customer,NaN,0
13,NaN,W 20 St & 7 Ave,NaN,8,-73.997262,374,2015-02-01 17:48:00+00,2015-02-01 17:55:00+00,334,5067,40.742388,497,E 17 St & Broadway,40.737050,-73.990093,21456,Customer,NaN,0
14,NaN,E 11 St & 1 Ave,NaN,9,-73.984267,420,2015-02-01 19:26:00+00,2015-02-01 19:33:00+00,326,5748,40.729538,527,E 33 St & 2 Ave,40.744023,-73.976056,14878,Subscriber,1988.0,1
15,NaN,W 24 St & 7 Ave,NaN,10,-73.995299,315,2015-02-01 21:34:00+00,2015-02-01 21:39:00+00,446,6086,40.744876,521,8 Ave & W 31 St,40.750450,-73.994811,16042,Subscriber,1956.0,1
16,NaN,8 Ave & W 31 St,NaN,70,-73.994811,801,2015-02-01 00:00:00+00,2015-02-01 00:14:00+00,521,1,40.750450,423,W 54 St & 9 Ave,40.765849,-73.986905,17131,Subscriber,1978.0,2
17,NaN,E 17 St & Broadway,NaN,71,-73.990093,379,2015-02-01 00:00:00+00,2015-02-01 00:07:00+00,497,2,40.737050,504,1 Ave & E 15 St,40.732219,-73.981656,21289,Subscriber,1993.0,1
18,NaN,Grand Army Plaza & Central Park S,NaN,72,-73.973715,2474,2015-02-01 00:01:00+00,2015-02-01 00:42:00+00,281,3,40.764397,127,Barrow St & Hudson St,40.731724,-74.006744,18903,Subscriber,1969.0,2
19,NaN,6 Ave & Broome St,NaN,73,-74.004704,818,2015-02-01 00:01:00+00,2015-02-01 00:15:00+00,2004,4,40.724399,505,6 Ave & W 33 St,40.749013,-73.988484,21044,Subscriber,1985.0,2
20,NaN,Lawrence St & Willoughby St,NaN,74,-73.986317,544,2015-02-01 00:01:00+00,2015-02-01 00:10:00+00,323,5,40.692362,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,19868,Subscriber,1957.0,1
21,NaN,Willoughby Ave & Walworth St,NaN,75,-73.953820,717,2015-02-01 00:02:00+00,2015-02-01 00:14:00+00,373,6,40.693317,2002,Wythe Ave & Metropolitan Ave,40.716887,-73.963198,15854,Subscriber,1979.0,1
22,NaN,W 56 St & 6 Ave,NaN,76,-73.977225,1306,2015-02-01 00:04:00+00,2015-02-01 00:26:00+00,352,7,40.763406,504,1 Ave & E 15 St,40.732219,-73.981656,15173,Subscriber,1983.0,1
23,NaN,E 4 St & 2 Ave,NaN,77,-73.989780,913,2015-02-01 00:04:00+00,2015-02-01 00:19:00+00,439,8,40.726281,116,W 17 St & 8 Ave,40.741776,-74.001497,17862,Subscriber,1955.0,1
24,NaN,Washington Pl & Broadway,NaN,78,-73.994046,759,2015-02-01 00:04:00+00,2015-02-01 00:17:00+00,335,9,40.729039,2012,E 27 St & 1 Ave,40.739445,-73.976806,21183,Subscriber,1985.0,2
25,NaN,Greenwich Ave & 8 Ave,NaN,79,-74.002638,585,2015-02-01 00:05:00+00,2015-02-01 00:15:00+00,284,10,40.739017,444,Broadway & W 24 St,40.742354,-73.989151,14843,Subscriber,1982.0,1
26,NaN,Greenwich Ave & 8 Ave,NaN,80,-74.002638,581,2015-02-01 00:05:00+00,2015-02-01 00:15:00+00,284,11,40.739017,444,Broadway & W 24 St,40.742354,-73.989151,16936,Subscriber,1988.0,2
27,NaN,Broadway & W 32 St,NaN,81,-73.988084,204,2015-02-01 00:05:00+00,2015-02-01 00:08:00+00,498,12,40.748549,472,E 32 St & Park Ave,40.745712,-73.981948,21507,Subscriber,1991.0,2
28,NaN,Carmine St & 6 Ave,NaN,82,-74.002150,1169,2015-02-01 00:07:00+00,2015-02-01 00:27:00+00,368,13,40.730386,307,Canal St & Rutgers St,40.714275,-73.989900,17456,Subscriber,1982.0,2
29,NaN,E 11 St & 1 Ave,NaN,83,-73.984267,419,2015-02-01 00:07:00+00,2015-02-01 00:14:00+00,326,14,40.729538,2012,E 27 St & 1 Ave,40.739445,-73.976806,14679,Subscriber,1990.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6411,NaN,Broadway & E 14 St,NaN,6480,-73.990741,440,2015-02-01 23:40:00+00,2015-02-01 23:48:00+00,285,6412,40.734546,2012,E 27 St & 1 Ave,40.739445,-73.976806,18791,Subscriber,1983.0,1
6412,NaN,Bank St & Washington St,NaN,6481,-74.008592,212,2015-02-01 23:40:00+00,2015-02-01 23:43:00+00,238,6413,40.736197,284,Greenwich Ave & 8 Ave,40.739017,-74.002638,20331,Subscriber,1989.0,1
6413,NaN,E 3 St & 1 Ave,NaN,6482,-73.987834,374,2015-02-01 23:41:00+00,2015-02-01 23:47:00+00,428,6414,40.724677,336,Sullivan St & Washington Sq,40.730477,-73.999061,16237,Subscriber,1981.0,1
6414,NaN,Canal St & Rutgers St,NaN,6483,-73.989900,154,2015-02-01 23:41:00+00,2015-02-01 23:44:00+00,307,6415,40.714275,291,Madison St & Montgomery St,40.713126,-73.984844,17086,Subscriber,1994.0,1
6415,NaN,E 16 St & Irving Pl,NaN,6484,-73.987586,618,2015-02-01 23:42:00+00,2015-02-01 23:52:00+00,475,6416,40.735243,518,E 39 St & 2 Ave,40.747804,-73.973442,21279,Subscriber,1980.0,1
6416,NaN,Elizabeth St & Hester St,NaN,6485,-73.996375,593,2015-02-01 23:42:00+00,2015-02-01 23:51:00+00,263,6417,40.717290,502,Henry St & Grand St,40.714215,-73.981346,18187,Subscriber,1966.0,1
6417,NaN,E 37 St & Lexington Ave,NaN,6486,-73.978311,542,2015-02-01 23:42:00+00,2015-02-01 23:51:00+00,160,6418,40.748238,487,E 20 St & FDR Drive,40.733143,-73.975739,14640,Subscriber,1988.0,1
6418,NaN,Carmine St & 6 Ave,NaN,6487,-74.002150,484,2015-02-01 23:42:00+00,2015-02-01 23:50:00+00,368,6419,40.730386,237,E 11 St & 2 Ave,40.730473,-73.986724,17388,Subscriber,1995.0,1
6419,NaN,E 24 St & Park Ave S,NaN,6488,-73.986022,399,2015-02-01 23:42:00+00,2015-02-01 23:48:00+00,491,6420,40.740964,527,E 33 St & 2 Ave,40.744023,-73.976056,18252,Subscriber,1989.0,1
6420,NaN,8 Ave & W 33 St,NaN,6489,-73.993934,723,2015-02-01 23:43:00+00,2015-02-01 23:55:00+00,490,6421,40.751551,513,W 56 St & 10 Ave,40.768254,-73.988639,20849,Subscriber,1984.0,1
6421,NaN,W 33 St & 7 Ave,NaN,6490,-73.990931,356,2015-02-01 23:43:00+00,2015-02-01 23:49:00+00,492,6422,40.750200,476,E 31 St & 3 Ave,40.743943,-73.979661,20751,Subscriber,1986.0,1
6422,NaN,8 Ave & W 33 St,NaN,6491,-73.993934,483,2015-02-01 23:45:00+00,2015-02-01 23:53:00+00,490,6423,40.751551,447,8 Ave & W 52 St,40.763707,-73.985162,18285,Subscriber,1979.0,1
6423,NaN,Greenwich St & N Moore St,NaN,6492,-74.010206,476,2015-02-01 23:48:00+00,2015-02-01 23:56:00+00,329,6424,40.720434,346,Bank St & Hudson St,40.736529,-74.006180,21501,Subscriber,1981.0,1
6424,NaN,E 6 St & Avenue B,NaN,6493,-73.981854,180,2015-02-01 23:48:00+00,2015-02-01 23:51:00+00,317,6425,40.724537,411,E 6 St & Avenue D,40.722281,-73.976687,20797,Subscriber,1988.0,1
6425,NaN,Greenwich St & N Moore St,NaN,6494,-74.010206,597,2015-02-01 23:49:00+00,2015-02-01 23:59:00+00,329,6426,40.720434,368,Carmine St & 6 Ave,40.730386,-74.002150,20267,Subscriber,1972.0,2
6426,NaN,E 43 St & Vanderbilt Ave,NaN,6495,-73.977987,563,2015-02-01 23:49:00+00,2015-02-01 23:58:00+00,318,6427,40.753202,488,W 39 St & 9 Ave,40.756458,-73.993722,14608,Subscriber,1958.0,1
6427,NaN,University Pl & E 14 St,NaN,6496,-73.992005,260,2015-02-01 23:49:00+00,2015-02-01 23:53:00+00,382,6428,40.734927,383,Greenwich Ave & Charles St,40.735238,-74.000271,16957,Subscriber,1962.0,2
6428,NaN,Greenwich St & N Moore St,NaN,6497,-74.010206,1315,2015-02-01 23:51:00+00,2015-02-02 00:13:00+00,329,6429,40.720434,329,Greenwich St & N Moore St,40.720434,-74.010206,17367,Subscriber,1969.0,1
6429,NaN,Allen St & E Houston St,NaN,6498,-73.989111,431,2015-02-01 23:52:00+00,2015-02-01 23:59:00+00,312,6430,40.722055,393,E 5 St & Avenue C,40.722992,-73.979955,15443,Subscriber,1978.0,1
6430,NaN,Canal St & Rutgers St,NaN,6499,-73.989900,773,2015-02-01 23:53:00+00,2015-02-02 00:06:00+00,307,6431,40.714275,127,Barrow St & Hudson St,40.731724,-74.006744,16425,Subscriber,1978.0,1
6431,NaN,9 Ave & W 14 St,NaN,6500,-74.005509,269,2015-02-01 23:53:00+00,2015-02-01 23:57:00+00,404,6432,40.740583,247,Perry St & Bleecker St,40.735354,-74.004831,19073,Subscriber,1976.0,1
6432,NaN,8 Ave & W 31 St,NaN,6501,-73.994811,667,2015-02-01 23:54:00+00,2015-02-02 00:05:00+00,521,6433,40.750450,513,W 56 St & 10 Ave,40.768254,-73.988639,15056,Subscriber,1984.0,1
6433,NaN,W 53 St & 10 Ave,NaN,6502,-73.990617,120,2015-02-01 23:54:00+00,2015-02-01 23:56:00+00,480,6434,40.766697,423,W 54 St & 9 Ave,40.765849,-73.986905,14704,Subscriber,1973.0,1
6434,NaN,Front St & Gold St,NaN,6503,-73.982578,408,2015-02-01 23:55:00+00,2015-02-02 00:01:00+00,418,6435,40.702240,322,Clinton St & Tillary St,40.696192,-73.991218,19251,Subscriber,1974.0,1
6435,NaN,8 Ave & W 31 St,NaN,6504,-73.994811,1523,2015-02-01 23:56:00+00,2015-02-02 00:22:00+00,521,6436,40.750450,3002,South End Ave & Liberty St,40.711512,-74.015756,18107,Subscriber,1968.0,1
6436,NaN,E 47 St & 2 Ave,NaN,6505,-73.970325,608,2015-02-01 23:56:00+00,2015-02-02 00:06:00+00,164,6437,40.753231,479,9 Ave & W 45 St,40.760193,-73.991255,16365,Subscriber,1983.0,1
6437,NaN,Shevchenko Pl & E 7 St,NaN,6506,-73.990214,340,2015-02-01 23:57:00+00,2015-02-02 00:02:00+00,300,6438,40.728145,393,E 5 St & Avenue C,40.722992,-73.979955,21202,Subscriber,1984.0,1
6438,NaN,E 53 St & Lexington Ave,NaN,6507,-73.970694,1604,2015-02-01 23:58:00+00,2015-02-02 00:25:00+00,367,6439,40.758281,428,E 3 St & 1 Ave,40.724677,-73.987834,16593,Subscriber,1961.0,1
6439,NaN,Allen St & Hester St,NaN,6508,-73.991908,428,2015-02-01 23:58:00+00,2015-02-02 00:05:00+00,361,6440,40.716059,400,Pitt St & Stanton St,40.719261,-73.981780,16787,Subscriber,1988.0,1
6440,NaN,Broadway & W 51 St,NaN,6509,-73.983362,398,2015-02-01 23:59:00+00,2015-02-02 00:05:00+00,500,6441,40.762288,72,W 52 St & 11 Ave,40.767272,-73.993929,21223,Subscriber,1974.0,1

In [129]:
test = '''SELECT * FROM citibike
WHERE starttime >= '2/7/2015 0:00'
and starttime <= '2/7/2015 23:59'
'''

table = get_data(test)
table

,the_geom,start_station_name,the_geom_webmercator,field_1,start_station_longitude,tripduration,starttime,stoptime,start_station_id,cartodb_id,start_station_latitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,E 20 St & 2 Ave,NaN,39894,-73.982050,296,2015-02-07 08:13:00+00,2015-02-07 08:18:00+00,461,39876,40.735877,435,W 21 St & 6 Ave,40.741740,-73.994156,17278,Subscriber,1987.0,1
1,NaN,Broadway & W 60 St,NaN,41512,-73.981918,600,2015-02-07 12:35:00+00,2015-02-07 12:45:00+00,499,41501,40.769155,523,W 38 St & 8 Ave,40.754666,-73.991382,15224,Subscriber,1959.0,1
2,NaN,E 6 St & Avenue D,NaN,41595,-73.976687,1203,2015-02-07 12:47:00+00,2015-02-07 13:07:00+00,411,41585,40.722281,428,E 3 St & 1 Ave,40.724677,-73.987834,21461,Subscriber,1968.0,1
3,NaN,Great Jones St,NaN,41806,-73.993790,520,2015-02-07 13:16:00+00,2015-02-07 13:25:00+00,229,41796,40.727434,168,W 18 St & 6 Ave,40.739713,-73.994564,14621,Subscriber,1964.0,1
4,NaN,W 13 St & 6 Ave,NaN,42316,-73.997044,487,2015-02-07 14:18:00+00,2015-02-07 14:26:00+00,345,42307,40.736494,509,9 Ave & W 22 St,40.745497,-74.001971,21362,Subscriber,1962.0,1
5,NaN,W 34 St & 11 Ave,NaN,42532,-74.002116,984,2015-02-07 14:42:00+00,2015-02-07 14:59:00+00,525,42523,40.755942,388,W 26 St & 10 Ave,40.749718,-74.002950,14549,Customer,NaN,0
6,NaN,W 41 St & 8 Ave,NaN,42915,-73.990026,621,2015-02-07 15:23:00+00,2015-02-07 15:33:00+00,477,42906,40.756405,509,9 Ave & W 22 St,40.745497,-74.001971,20216,Subscriber,1980.0,1
7,NaN,E 25 St & 1 Ave,NaN,44448,-73.977387,397,2015-02-07 18:03:00+00,2015-02-07 18:10:00+00,174,44443,40.738177,528,2 Ave & E 31 St,40.742909,-73.977061,15948,Subscriber,1991.0,1
8,NaN,E 15 St & 3 Ave,NaN,44744,-73.986923,352,2015-02-07 18:39:00+00,2015-02-07 18:45:00+00,297,44739,40.734232,507,E 25 St & 2 Ave,40.739126,-73.979738,15367,Subscriber,1978.0,1
9,NaN,W 33 St & 7 Ave,NaN,44834,-73.990931,1063,2015-02-07 18:53:00+00,2015-02-07 19:11:00+00,492,44829,40.750200,174,E 25 St & 1 Ave,40.738177,-73.977387,20702,Subscriber,1989.0,2
10,NaN,E 33 St & 2 Ave,NaN,45301,-73.976056,483,2015-02-07 19:59:00+00,2015-02-07 20:07:00+00,527,45297,40.744023,325,E 19 St & 3 Ave,40.736245,-73.984738,20296,Subscriber,1984.0,1
11,NaN,W 33 St & 7 Ave,NaN,38,-73.990931,302,2015-02-07 06:33:00+00,2015-02-07 06:38:00+00,492,39722,40.750200,493,W 45 St & 6 Ave,40.756800,-73.982912,18472,Subscriber,1972.0,1
12,NaN,W 17 St & 8 Ave,NaN,49,-74.001497,424,2015-02-07 00:00:00+00,2015-02-07 00:07:00+00,116,39412,40.741776,489,10 Ave & W 28 St,40.750664,-74.001768,19071,Subscriber,1963.0,1
13,NaN,E 15 St & 3 Ave,NaN,50,-73.986923,439,2015-02-07 03:43:00+00,2015-02-07 03:50:00+00,297,39651,40.734232,527,E 33 St & 2 Ave,40.744023,-73.976056,21448,Customer,NaN,0
14,NaN,W 15 St & 7 Ave,NaN,51,-73.999318,463,2015-02-07 09:16:00+00,2015-02-07 09:24:00+00,482,40142,40.739355,267,Broadway & W 36 St,40.750977,-73.987654,17278,Subscriber,1986.0,1
15,NaN,1 Ave & E 15 St,NaN,52,-73.981656,852,2015-02-07 09:32:00+00,2015-02-07 09:46:00+00,504,40225,40.732219,459,W 20 St & 11 Ave,40.746745,-74.007756,20618,Subscriber,1960.0,2
16,NaN,E 47 St & 1 Ave,NaN,53,-73.967844,2049,2015-02-07 10:35:00+00,2015-02-07 11:09:00+00,516,40705,40.752069,484,W 44 St & 5 Ave,40.755003,-73.980144,21066,Customer,NaN,0
17,NaN,W 21 St & 6 Ave,NaN,54,-73.994156,400,2015-02-07 11:31:00+00,2015-02-07 11:38:00+00,435,41101,40.741740,533,Broadway & W 39 St,40.752996,-73.987216,16087,Subscriber,1971.0,1
18,NaN,6 Ave & Canal St,NaN,55,-74.005664,1597,2015-02-07 11:57:00+00,2015-02-07 12:24:00+00,377,41270,40.722438,2021,W 45 St & 8 Ave,40.759291,-73.988597,17877,Customer,NaN,0
19,NaN,E 17 St & Broadway,NaN,56,-73.990093,996,2015-02-07 12:37:00+00,2015-02-07 12:53:00+00,497,41517,40.737050,494,W 26 St & 8 Ave,40.747348,-73.997236,21527,Subscriber,1990.0,1
20,NaN,E 19 St & 3 Ave,NaN,57,-73.984738,1640,2015-02-07 14:01:00+00,2015-02-07 14:28:00+00,325,42172,40.736245,301,E 2 St & Avenue B,40.722174,-73.983688,16077,Customer,NaN,0
21,NaN,E 5 St & Avenue C,NaN,58,-73.979955,493,2015-02-07 15:40:00+00,2015-02-07 15:48:00+00,393,43056,40.722992,504,1 Ave & E 15 St,40.732219,-73.981656,19574,Subscriber,1972.0,1
22,NaN,Broadway & W 51 St,NaN,59,-73.983362,2092,2015-02-07 16:50:00+00,2015-02-07 17:25:00+00,500,43762,40.762288,447,8 Ave & W 52 St,40.763707,-73.985162,18605,Subscriber,1975.0,1
23,NaN,W 42 St & 8 Ave,NaN,60,-73.990985,1104,2015-02-07 17:23:00+00,2015-02-07 17:41:00+00,529,44093,40.757570,463,9 Ave & W 16 St,40.742065,-74.004432,18767,Customer,NaN,0
24,NaN,Cherry St,NaN,61,-73.979481,1526,2015-02-07 17:34:00+00,2015-02-07 18:00:00+00,332,44199,40.712199,167,E 39 St & 3 Ave,40.748901,-73.976049,16019,Subscriber,1983.0,1
25,NaN,W 13 St & 6 Ave,NaN,62,-73.997044,237,2015-02-07 18:55:00+00,2015-02-07 18:59:00+00,345,44841,40.736494,435,W 21 St & 6 Ave,40.741740,-73.994156,17289,Subscriber,1958.0,1
26,NaN,W 17 St & 8 Ave,NaN,63,-74.001497,120,2015-02-07 20:08:00+00,2015-02-07 20:10:00+00,116,45343,40.741776,434,9 Ave & W 18 St,40.743174,-74.003664,19701,Subscriber,1978.0,1
27,NaN,E 11 St & 2 Ave,NaN,64,-73.986724,558,2015-02-07 20:16:00+00,2015-02-07 20:26:00+00,237,45383,40.730473,435,W 21 St & 6 Ave,40.741740,-73.994156,18941,Subscriber,1988.0,1
28,NaN,E 2 St & 2 Ave,NaN,65,-73.990697,416,2015-02-07 20:45:00+00,2015-02-07 20:52:00+00,403,45506,40.725029,285,Broadway & E 14 St,40.734546,-73.990741,20622,Subscriber,1993.0,1
29,NaN,W 13 St & 6 Ave,NaN,66,-73.997044,320,2015-02-07 21:30:00+00,2015-02-07 21:35:00+00,345,45672,40.736494,475,E 16 St & Irving Pl,40.735243,-73.987586,15403,Subscriber,1987.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6760,NaN,Washington Pl & Broadway,NaN,46170,-73.994046,812,2015-02-07 23:51:00+00,2015-02-08 00:05:00+00,335,46171,40.729039,435,W 21 St & 6 Ave,40.741740,-73.994156,15733,Subscriber,1988.0,1
6761,NaN,Allen St & Hester St,NaN,46171,-73.991908,647,2015-02-07 23:51:00+00,2015-02-08 00:02:00+00,361,46172,40.716059,504,1 Ave & E 15 St,40.732219,-73.981656,16931,Subscriber,1995.0,1
6762,NaN,Warren St & Church St,NaN,46172,-74.009106,563,2015-02-07 23:51:00+00,2015-02-08 00:00:00+00,152,46173,40.714740,401,Allen St & Rivington St,40.720196,-73.989978,17202,Subscriber,1987.0,1
6763,NaN,E 12 St & 3 Ave,NaN,46173,-73.988900,470,2015-02-07 23:51:00+00,2015-02-07 23:59:00+00,483,46174,40.732233,439,E 4 St & 2 Ave,40.726281,-73.989780,20314,Subscriber,1989.0,2
6764,NaN,Dean St & 4 Ave,NaN,46174,-73.978951,299,2015-02-07 23:51:00+00,2015-02-07 23:56:00+00,467,46175,40.683125,395,Bond St & Schermerhorn St,40.688070,-73.984106,21531,Subscriber,1989.0,1
6765,NaN,Allen St & Hester St,NaN,46175,-73.991908,629,2015-02-07 23:52:00+00,2015-02-08 00:02:00+00,361,46176,40.716059,504,1 Ave & E 15 St,40.732219,-73.981656,21491,Subscriber,1968.0,1
6766,NaN,Broadway & E 22 St,NaN,46176,-73.989551,499,2015-02-07 23:52:00+00,2015-02-08 00:00:00+00,402,46177,40.740343,380,W 4 St & 7 Ave S,40.734011,-74.002939,15367,Subscriber,1990.0,1
6767,NaN,Washington Pl & 6 Ave,NaN,46177,-74.000264,474,2015-02-07 23:52:00+00,2015-02-08 00:00:00+00,369,46178,40.732241,368,Carmine St & 6 Ave,40.730386,-74.002150,18978,Subscriber,1973.0,2
6768,NaN,E 31 St & 3 Ave,NaN,46178,-73.979661,345,2015-02-07 23:52:00+00,2015-02-07 23:58:00+00,476,46179,40.743943,504,1 Ave & E 15 St,40.732219,-73.981656,19507,Subscriber,1980.0,1
6769,NaN,Broadway & W 60 St,NaN,46179,-73.981918,829,2015-02-07 23:53:00+00,2015-02-08 00:07:00+00,499,46180,40.769155,160,E 37 St & Lexington Ave,40.748238,-73.978311,16936,Subscriber,1980.0,1
6770,NaN,Carmine St & 6 Ave,NaN,46180,-74.002150,776,2015-02-07 23:53:00+00,2015-02-08 00:05:00+00,368,46181,40.730386,531,Forsyth St & Broome St,40.718939,-73.992663,18689,Subscriber,1982.0,1
6771,NaN,W 52 St & 5 Ave,NaN,46181,-73.976485,697,2015-02-07 23:53:00+00,2015-02-08 00:05:00+00,520,46182,40.759923,478,11 Ave & W 41 St,40.760301,-73.998842,15781,Subscriber,1972.0,1
6772,NaN,Dean St & 4 Ave,NaN,46182,-73.978951,1703,2015-02-07 23:54:00+00,2015-02-08 00:23:00+00,467,46183,40.683125,471,Grand St & Havemeyer St,40.712868,-73.956981,15081,Subscriber,1988.0,1
6773,NaN,9 Ave & W 45 St,NaN,46183,-73.991255,922,2015-02-07 23:54:00+00,2015-02-08 00:10:00+00,479,46184,40.760193,247,Perry St & Bleecker St,40.735354,-74.004831,21672,Subscriber,1983.0,1
6774,NaN,Broadway & W 58 St,NaN,46184,-73.981693,849,2015-02-07 23:54:00+00,2015-02-08 00:08:00+00,457,46185,40.766953,488,W 39 St & 9 Ave,40.756458,-73.993722,16336,Subscriber,1970.0,1
6775,NaN,Broadway & W 58 St,NaN,46185,-73.981693,826,2015-02-07 23:54:00+00,2015-02-08 00:08:00+00,457,46186,40.766953,488,W 39 St & 9 Ave,40.756458,-73.993722,21609,Subscriber,1973.0,1
6776,NaN,Watts St & Greenwich St,NaN,46186,-74.009660,473,2015-02-07 23:54:00+00,2015-02-08 00:02:00+00,328,46187,40.724055,3002,South End Ave & Liberty St,40.711512,-74.015756,19470,Subscriber,1964.0,1
6777,NaN,W 51 St & 6 Ave,NaN,46187,-73.980420,332,2015-02-07 23:54:00+00,2015-02-07 23:59:00+00,510,46188,40.760660,450,W 49 St & 8 Ave,40.762272,-73.987882,18167,Subscriber,1960.0,1
6778,NaN,University Pl & E 14 St,NaN,46188,-73.992005,456,2015-02-07 23:55:00+00,2015-02-08 00:03:00+00,382,46189,40.734927,404,9 Ave & W 14 St,40.740583,-74.005509,15929,Subscriber,1987.0,1
6779,NaN,W 11 St & 6 Ave,NaN,46189,-73.998004,327,2015-02-07 23:55:00+00,2015-02-08 00:01:00+00,254,46190,40.735324,466,W 25 St & 6 Ave,40.743954,-73.991449,17541,Subscriber,1983.0,1
6780,NaN,W 17 St & 8 Ave,NaN,46190,-74.001497,306,2015-02-07 23:55:00+00,2015-02-08 00:01:00+00,116,46191,40.741776,494,W 26 St & 8 Ave,40.747348,-73.997236,14736,Subscriber,1983.0,2
6781,NaN,W 47 St & 10 Ave,NaN,46191,-73.993012,1248,2015-02-07 23:56:00+00,2015-02-08 00:17:00+00,495,46192,40.762699,432,E 7 St & Avenue A,40.726218,-73.983799,16300,Subscriber,1984.0,1
6782,NaN,Warren St & Church St,NaN,46192,-74.009106,1165,2015-02-07 23:56:00+00,2015-02-08 00:15:00+00,152,46193,40.714740,325,E 19 St & 3 Ave,40.736245,-73.984738,16978,Subscriber,1959.0,1
6783,NaN,E 20 St & 2 Ave,NaN,46193,-73.982050,993,2015-02-07 23:56:00+00,2015-02-08 00:13:00+00,461,46194,40.735877,295,Pike St & E Broadway,40.714067,-73.992939,16722,Subscriber,1974.0,1
6784,NaN,1 Ave & E 44 St,NaN,46194,-73.969053,1422,2015-02-07 23:57:00+00,2015-02-08 00:20:00+00,455,46195,40.750020,265,Stanton St & Chrystie St,40.722293,-73.991475,20184,Subscriber,1960.0,2
6785,NaN,W 20 St & 8 Ave,NaN,46195,-74.000040,689,2015-02-07 23:57:00+00,2015-02-08 00:08:00+00,470,46196,40.743453,325,E 19 St & 3 Ave,40.736245,-73.984738,15585,Subscriber,1953.0,1
6786,NaN,5 Ave & E 29 St,NaN,46196,-73.986831,428,2015-02-07 23:57:00+00,2015-02-08 00:04:00+00,474,46197,40.745168,325,E 19 St & 3 Ave,40.736245,-73.984738,16395,Subscriber,1986.0,2
6787,NaN,5 Ave & E 29 St,NaN,46197,-73.986831,392,2015-02-07 23:57:00+00,2015-02-08 00:03:00+00,474,46198,40.745168,325,E 19 St & 3 Ave,40.736245,-73.984738,15545,Subscriber,1986.0,1
6788,NaN,Carmine St & 6 Ave,NaN,46198,-74.002150,548,2015-02-07 23:58:00+00,2015-02-08 00:08:00+00,368,46199,40.730386,334,W 20 St & 7 Ave,40.742388,-73.997262,19540,Subscriber,1983.0,2
6789,NaN,E 4 St & 2 Ave,NaN,46199,-73.989780,917,2015-02-07 23:59:00+00,2015-02-08 00:15:00+00,439,46200,40.726281,417,Barclay St & Church St,40.712912,-74.010202,20998,Subscriber,1965.0,2

### What are average trip duration during weekends?

In [130]:
test = '''SELECT AVG(tripduration) FROM citibike
WHERE starttime >= '2/1/2015 0:00'
and starttime <= '2/1/2015 23:59'
'''

table = get_data(test)
print(table)


test = '''SELECT AVG(tripduration) FROM citibike
WHERE starttime >= '2/7/2015 0:00'
and starttime <= '2/7/2015 23:59'
'''

table = get_data(test)
print(table)

        avg  Unnamed: 1
0  638.1492         NaN
          avg  Unnamed: 1
0  686.460825         NaN

## Can we do the same for weekday?

In [131]:
test = '''SELECT AVG(tripduration) FROM citibike
WHERE starttime >= '2/2/2015 0:00'
and starttime <= '2/2/2015 23:59'
'''

table = get_data(test)
print(table)

test = '''SELECT AVG(tripduration) FROM citibike
WHERE starttime >= '2/3/2015 0:00'
and starttime <= '2/3/2015 23:59'
'''

table = get_data(test)
print(table)

test = '''SELECT AVG(tripduration) FROM citibike
WHERE starttime >= '2/4/2015 0:00'
and starttime <= '2/4/2015 23:59'
'''

table = get_data(test)
print(table)

test = '''SELECT AVG(tripduration) FROM citibike
WHERE starttime >= '2/5/2015 0:00'
and starttime <= '2/5/2015 23:59'
'''

table = get_data(test)
print(table)

test = '''SELECT AVG(tripduration) FROM citibike
WHERE starttime >= '2/6/2015 0:00'
and starttime <= '2/6/2015 23:59'
'''

table = get_data(test)
print(table)

          avg  Unnamed: 1
0  920.862234         NaN
          avg  Unnamed: 1
0  767.224443         NaN
          avg  Unnamed: 1
0  697.556559         NaN
         avg  Unnamed: 1
0  623.39672         NaN
          avg  Unnamed: 1
0  637.116968         NaN

# Task 3 — Working with Space

## Showing the list of start station locations
### Using GROUP BY

In [132]:
test = '''SELECT start_station_name FROM citibike
GROUP BY start_station_name 
'''
table = get_data(test)
table

                start_station_name  Unnamed: 1
0             E 30 St & Park Ave S         NaN
1          Pearl St & Anchorage Pl         NaN
2                  W 56 St & 6 Ave         NaN
3                   West Thames St         NaN
4          Bank St & Washington St         NaN
5                  8 Ave & W 52 St         NaN
6               E 11 St & Broadway         NaN
7         DeKalb Ave & Skillman St         NaN
8    Atlantic Ave & Fort Greene Pl         NaN
9                Avenue D & E 8 St         NaN
10            S 3 St & Bedford Ave         NaN
11          W Broadway & Spring St         NaN
12                 2 Ave & E 31 St         NaN
13                 E 33 St & 5 Ave         NaN
14        MacDougal St & Prince St         NaN
15    Clermont Ave & Lafayette Ave         NaN
16          Barclay St & Church St         NaN
17          Forsyth St & Broome St         NaN
18                 W 13 St & 6 Ave         NaN
19                 W 17 St & 8 Ave         NaN
20              E 20 St & Park Ave         NaN
21               E 2 St & Avenue B         NaN
22                 E 33 St & 2 Ave         NaN
23                 W 18 St & 6 Ave         NaN
24             Old Slip & Front St         NaN
25        Willoughby Ave & Hall St         NaN
26                 1 Ave & E 44 St         NaN
27                 W 20 St & 7 Ave         NaN
28           West St & Chambers St         NaN
29                 E 43 St & 2 Ave         NaN
..                             ...         ...
297               12 Ave & W 40 St         NaN
298        Centre St & Chambers St         NaN
299          Pershing Square South         NaN
300                W 33 St & 7 Ave         NaN
301         Hicks St & Montague St         NaN
302        University Pl & E 14 St         NaN
303        Fulton St & Rockwell Pl         NaN
304    Lafayette Ave & St James Pl         NaN
305        Emerson Pl & Myrtle Ave         NaN
306                E 56 St & 3 Ave         NaN
307        Watts St & Greenwich St         NaN
308                W 44 St & 5 Ave         NaN
309                6 Ave & W 33 St         NaN
310              E 9 St & Avenue C         NaN
311               11 Ave & W 59 St         NaN
312        W 16 St & The High Line         NaN
313          Howard St & Centre St         NaN
314                2 Ave & E 58 St         NaN
315              E 5 St & Avenue C         NaN
316       Fulton St & Clermont Ave         NaN
317    Cadman Plaza E & Tillary St         NaN
318      Pearl St & Hanover Square         NaN
319          LaGuardia Pl & W 3 St         NaN
320                5 Ave & E 29 St         NaN
321                W 21 St & 6 Ave         NaN
322   Wythe Ave & Metropolitan Ave         NaN
323                W 11 St & 6 Ave         NaN
324            St Marks Pl & 1 Ave         NaN
325                W 22 St & 8 Ave         NaN
326         Railroad Ave & Kay Ave         NaN

[327 rows x 2 columns]

## Showing the number of trips started per station

In [133]:
test = '''SELECT start_station_name, COUNT(cartodb_id) FROM citibike
GROUP BY start_station_name 
'''
table = get_data(test)
table

                start_station_name  count
0             E 30 St & Park Ave S    227
1          Pearl St & Anchorage Pl     54
2                  W 56 St & 6 Ave    164
3                   West Thames St    107
4          Bank St & Washington St    125
5                  8 Ave & W 52 St    133
6               E 11 St & Broadway    115
7         DeKalb Ave & Skillman St     10
8    Atlantic Ave & Fort Greene Pl     36
9                Avenue D & E 8 St     38
10            S 3 St & Bedford Ave     13
11          W Broadway & Spring St    159
12                 2 Ave & E 31 St    302
13                 E 33 St & 5 Ave    213
14        MacDougal St & Prince St    247
15    Clermont Ave & Lafayette Ave     25
16          Barclay St & Church St    244
17          Forsyth St & Broome St    212
18                 W 13 St & 6 Ave    257
19                 W 17 St & 8 Ave    288
20              E 20 St & Park Ave    218
21               E 2 St & Avenue B    199
22                 E 33 St & 2 Ave    319
23                 W 18 St & 6 Ave    327
24             Old Slip & Front St     60
25        Willoughby Ave & Hall St     35
26                 1 Ave & E 44 St    110
27                 W 20 St & 7 Ave    190
28           West St & Chambers St    162
29                 E 43 St & 2 Ave     86
..                             ...    ...
297               12 Ave & W 40 St     91
298        Centre St & Chambers St    159
299          Pershing Square South    362
300                W 33 St & 7 Ave    309
301         Hicks St & Montague St     64
302        University Pl & E 14 St    341
303        Fulton St & Rockwell Pl     37
304    Lafayette Ave & St James Pl     32
305        Emerson Pl & Myrtle Ave     30
306                E 56 St & 3 Ave     41
307        Watts St & Greenwich St     73
308                W 44 St & 5 Ave    137
309                6 Ave & W 33 St    296
310              E 9 St & Avenue C    201
311               11 Ave & W 59 St    120
312        W 16 St & The High Line    186
313          Howard St & Centre St    124
314                2 Ave & E 58 St     64
315              E 5 St & Avenue C    142
316       Fulton St & Clermont Ave     27
317    Cadman Plaza E & Tillary St     22
318      Pearl St & Hanover Square     97
319          LaGuardia Pl & W 3 St    203
320                5 Ave & E 29 St    230
321                W 21 St & 6 Ave    519
322   Wythe Ave & Metropolitan Ave     45
323                W 11 St & 6 Ave    108
324            St Marks Pl & 1 Ave    156
325                W 22 St & 8 Ave    218
326         Railroad Ave & Kay Ave      7

[327 rows x 2 columns]

## Only for stations within 500m of Time Square

In [134]:
test = '''SELECT start_station_name, COUNT(cartodb_id),
(SQRT(POWER(start_station_latitude - 40.7577, 2) + POWER(start_station_longitude + 73.9857,2)) * 100000) AS RADIUS
FROM citibike
WHERE (SQRT(POWER(start_station_latitude - 40.7577, 2) + POWER(start_station_longitude + 73.9857,2)) * 100000) < 500
GROUP BY start_station_name, start_station_latitude, start_station_longitude
ORDER BY RADIUS
'''
table = get_data(test)
table

   start_station_name  count      radius
0  Broadway & W 41 St    251  271.132155
1     W 45 St & 6 Ave    141  293.008275
2  Broadway & W 49 St    213  321.016266
3     W 45 St & 8 Ave    141  330.481693
4     W 43 St & 6 Ave    112  350.629834
5     W 41 St & 8 Ave    507  451.572679
6  Broadway & W 39 St    196  494.192179

# Task 4 — Putting it all together
## Find the station that had the longest average trip duration during weekends and within 500m of TimeSquare

In [135]:
test = '''SELECT start_station_name, AVG(tripduration) as tripduration FROM citibike
WHERE (SQRT(POWER(start_station_latitude - 40.7577, 2) + POWER(start_station_longitude + 73.9857,2)) * 100000) < 500
and starttime >= '2/1/2015 0:00'
and starttime <= '2/1/2015 23:59'
GROUP BY start_station_name, start_station_latitude, start_station_longitude
ORDER BY tripduration ASC 
LIMIT 1;'''
table = get_data(test)
table

  start_station_name  tripduration
0    W 43 St & 6 Ave         410.5

In [136]:
test = '''SELECT start_station_name, AVG(tripduration) as tripduration FROM citibike
WHERE (SQRT(POWER(start_station_latitude - 40.7577, 2) + POWER(start_station_longitude + 73.9857,2)) * 100000) < 500
and starttime >= '2/7/2015 0:00'
and starttime <= '2/7/2015 23:59'
GROUP BY start_station_name, start_station_latitude, start_station_longitude
ORDER BY tripduration ASC 
LIMIT 1;'''
table = get_data(test)
table

  start_station_name  tripduration
0    W 41 St & 8 Ave    640.142857

# extra credit: make the function python 2 and 3 compatible so that it works on the  PUI2016_Python3 kernel